package dbschema

// Column describes the lossless import representation. Identity columns are reseeded after import.
type Column struct {
	Name     string
	Type     string
	Identity bool
}
type Table struct {
	Name    string
	Columns []Column
}

// Tables is the complete telemetry import manifest, in dependency order.
var Tables = []Table{
	{Name: "nodes", Columns: []Column{{Name: "public_key", Type: "TEXT", Identity: false}, {Name: "name", Type: "TEXT", Identity: false}, {Name: "role", Type: "TEXT", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "last_seen", Type: "TEXT", Identity: false}, {Name: "first_seen", Type: "TEXT", Identity: false}, {Name: "advert_count", Type: "BIGINT", Identity: false}, {Name: "battery_mv", Type: "BIGINT", Identity: false}, {Name: "temperature_c", Type: "DOUBLE PRECISION", Identity: false}, {Name: "foreign_advert", Type: "BIGINT", Identity: false}, {Name: "default_scope", Type: "TEXT", Identity: false}, {Name: "configured_scope", Type: "TEXT", Identity: false}, {Name: "configured_scope_at", Type: "TEXT", Identity: false}, {Name: "multibyte_sup", Type: "BIGINT", Identity: false}, {Name: "multibyte_evidence", Type: "TEXT", Identity: false}}},
	{Name: "inactive_nodes", Columns: []Column{{Name: "public_key", Type: "TEXT", Identity: false}, {Name: "name", Type: "TEXT", Identity: false}, {Name: "role", Type: "TEXT", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "last_seen", Type: "TEXT", Identity: false}, {Name: "first_seen", Type: "TEXT", Identity: false}, {Name: "advert_count", Type: "BIGINT", Identity: false}, {Name: "battery_mv", Type: "BIGINT", Identity: false}, {Name: "temperature_c", Type: "DOUBLE PRECISION", Identity: false}, {Name: "foreign_advert", Type: "BIGINT", Identity: false}, {Name: "default_scope", Type: "TEXT", Identity: false}, {Name: "configured_scope", Type: "TEXT", Identity: false}, {Name: "configured_scope_at", Type: "TEXT", Identity: false}, {Name: "multibyte_sup", Type: "BIGINT", Identity: false}, {Name: "multibyte_evidence", Type: "TEXT", Identity: false}}},
	{Name: "observers", Columns: []Column{{Name: "rowid", Type: "BIGINT", Identity: true}, {Name: "id", Type: "TEXT", Identity: false}, {Name: "name", Type: "TEXT", Identity: false}, {Name: "iata", Type: "TEXT", Identity: false}, {Name: "last_seen", Type: "TEXT", Identity: false}, {Name: "first_seen", Type: "TEXT", Identity: false}, {Name: "packet_count", Type: "BIGINT", Identity: false}, {Name: "model", Type: "TEXT", Identity: false}, {Name: "firmware", Type: "TEXT", Identity: false}, {Name: "client_version", Type: "TEXT", Identity: false}, {Name: "radio", Type: "TEXT", Identity: false}, {Name: "battery_mv", Type: "BIGINT", Identity: false}, {Name: "uptime_secs", Type: "BIGINT", Identity: false}, {Name: "noise_floor", Type: "DOUBLE PRECISION", Identity: false}, {Name: "inactive", Type: "BIGINT", Identity: false}, {Name: "last_packet_at", Type: "TEXT", Identity: false}, {Name: "clock_skew_seconds", Type: "BIGINT", Identity: false}, {Name: "clock_skew_count_24h", Type: "BIGINT", Identity: false}, {Name: "clock_last_naive_at", Type: "TEXT", Identity: false}, {Name: "can_relay", Type: "BIGINT", Identity: false}, {Name: "can_relay_seen", Type: "BIGINT", Identity: false}}},
	{Name: "transmissions", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "raw_hex", Type: "TEXT", Identity: false}, {Name: "hash", Type: "TEXT", Identity: false}, {Name: "first_seen", Type: "TEXT", Identity: false}, {Name: "route_type", Type: "BIGINT", Identity: false}, {Name: "payload_type", Type: "BIGINT", Identity: false}, {Name: "payload_version", Type: "BIGINT", Identity: false}, {Name: "decoded_json", Type: "TEXT", Identity: false}, {Name: "from_pubkey", Type: "TEXT", Identity: false}, {Name: "last_seen", Type: "BIGINT", Identity: false}, {Name: "created_at", Type: "TEXT", Identity: false}, {Name: "code1", Type: "TEXT", Identity: false}, {Name: "code2", Type: "TEXT", Identity: false}, {Name: "channel_hash", Type: "TEXT", Identity: false}, {Name: "scope_name", Type: "TEXT", Identity: false}}},
	{Name: "observations", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "transmission_id", Type: "BIGINT", Identity: false}, {Name: "observer_idx", Type: "BIGINT", Identity: false}, {Name: "direction", Type: "TEXT", Identity: false}, {Name: "snr", Type: "DOUBLE PRECISION", Identity: false}, {Name: "rssi", Type: "DOUBLE PRECISION", Identity: false}, {Name: "score", Type: "DOUBLE PRECISION", Identity: false}, {Name: "path_json", Type: "TEXT", Identity: false}, {Name: "timestamp", Type: "BIGINT", Identity: false}, {Name: "raw_hex", Type: "TEXT", Identity: false}, {Name: "resolved_path", Type: "TEXT", Identity: false}}},
	{Name: "observer_metrics", Columns: []Column{{Name: "observer_id", Type: "TEXT", Identity: false}, {Name: "timestamp", Type: "TEXT", Identity: false}, {Name: "noise_floor", Type: "DOUBLE PRECISION", Identity: false}, {Name: "tx_air_secs", Type: "BIGINT", Identity: false}, {Name: "rx_air_secs", Type: "BIGINT", Identity: false}, {Name: "recv_errors", Type: "BIGINT", Identity: false}, {Name: "battery_mv", Type: "BIGINT", Identity: false}, {Name: "packets_sent", Type: "BIGINT", Identity: false}, {Name: "packets_recv", Type: "BIGINT", Identity: false}}},
	{Name: "neighbor_edges", Columns: []Column{{Name: "node_a", Type: "TEXT", Identity: false}, {Name: "node_b", Type: "TEXT", Identity: false}, {Name: "count", Type: "BIGINT", Identity: false}, {Name: "last_seen", Type: "TEXT", Identity: false}}},
	{Name: "dropped_packets", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "hash", Type: "TEXT", Identity: false}, {Name: "raw_hex", Type: "TEXT", Identity: false}, {Name: "reason", Type: "TEXT", Identity: false}, {Name: "observer_id", Type: "TEXT", Identity: false}, {Name: "observer_name", Type: "TEXT", Identity: false}, {Name: "node_pubkey", Type: "TEXT", Identity: false}, {Name: "node_name", Type: "TEXT", Identity: false}, {Name: "dropped_at", Type: "TEXT", Identity: false}}},
	{Name: "client_receptions", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "rx_pubkey", Type: "TEXT", Identity: false}, {Name: "heard_key", Type: "TEXT", Identity: false}, {Name: "heard_keylen", Type: "BIGINT", Identity: false}, {Name: "rssi", Type: "BIGINT", Identity: false}, {Name: "snr", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "pos_acc_m", Type: "DOUBLE PRECISION", Identity: false}, {Name: "rx_at", Type: "TEXT", Identity: false}, {Name: "ingested_at", Type: "TEXT", Identity: false}, {Name: "src", Type: "TEXT", Identity: false}}},
	{Name: "client_observers", Columns: []Column{{Name: "pubkey", Type: "TEXT", Identity: false}, {Name: "name", Type: "TEXT", Identity: false}, {Name: "last_seen", Type: "TEXT", Identity: false}}},
	{Name: "client_rx_observations", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "rx_pubkey", Type: "TEXT", Identity: false}, {Name: "rx_at", Type: "TEXT", Identity: false}, {Name: "ingested_at", Type: "TEXT", Identity: false}, {Name: "pkt_hash", Type: "TEXT", Identity: false}, {Name: "route_type", Type: "BIGINT", Identity: false}, {Name: "payload_type", Type: "BIGINT", Identity: false}, {Name: "code1", Type: "TEXT", Identity: false}, {Name: "code2", Type: "TEXT", Identity: false}, {Name: "scope_name", Type: "TEXT", Identity: false}, {Name: "hash_size", Type: "BIGINT", Identity: false}, {Name: "hop_count", Type: "BIGINT", Identity: false}, {Name: "path_json", Type: "TEXT", Identity: false}, {Name: "forwarder", Type: "TEXT", Identity: false}, {Name: "snr", Type: "DOUBLE PRECISION", Identity: false}, {Name: "rssi", Type: "BIGINT", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "pos_acc_m", Type: "DOUBLE PRECISION", Identity: false}}},
	{Name: "client_rf_samples", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "rx_pubkey", Type: "TEXT", Identity: false}, {Name: "sampled_at", Type: "TEXT", Identity: false}, {Name: "ingested_at", Type: "TEXT", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "pos_acc_m", Type: "DOUBLE PRECISION", Identity: false}, {Name: "stationary", Type: "BIGINT", Identity: false}, {Name: "uptime_secs", Type: "BIGINT", Identity: false}, {Name: "battery_mv", Type: "BIGINT", Identity: false}, {Name: "queue_len", Type: "BIGINT", Identity: false}, {Name: "errors", Type: "BIGINT", Identity: false}, {Name: "noise_floor", Type: "BIGINT", Identity: false}, {Name: "last_rssi", Type: "BIGINT", Identity: false}, {Name: "last_snr", Type: "DOUBLE PRECISION", Identity: false}, {Name: "tx_air_secs", Type: "BIGINT", Identity: false}, {Name: "rx_air_secs", Type: "BIGINT", Identity: false}, {Name: "recv", Type: "BIGINT", Identity: false}, {Name: "sent", Type: "BIGINT", Identity: false}, {Name: "flood_rx", Type: "BIGINT", Identity: false}, {Name: "direct_rx", Type: "BIGINT", Identity: false}, {Name: "flood_tx", Type: "BIGINT", Identity: false}, {Name: "direct_tx", Type: "BIGINT", Identity: false}, {Name: "recv_errors", Type: "BIGINT", Identity: false}}},
	{Name: "node_declared_regions", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "target", Type: "TEXT", Identity: false}, {Name: "rx_pubkey", Type: "TEXT", Identity: false}, {Name: "observed_at", Type: "TEXT", Identity: false}, {Name: "ingested_at", Type: "TEXT", Identity: false}, {Name: "regions_csv", Type: "TEXT", Identity: false}, {Name: "truncated", Type: "BIGINT", Identity: false}, {Name: "lat", Type: "DOUBLE PRECISION", Identity: false}, {Name: "lon", Type: "DOUBLE PRECISION", Identity: false}, {Name: "pos_acc_m", Type: "DOUBLE PRECISION", Identity: false}, {Name: "repeater_clock", Type: "BIGINT", Identity: false}}},
	{Name: "scope_match_totals", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: false}, {Name: "since_unix", Type: "BIGINT", Identity: false}, {Name: "unique_matches", Type: "BIGINT", Identity: false}, {Name: "explicit_over_derived", Type: "BIGINT", Identity: false}, {Name: "ambiguous", Type: "BIGINT", Identity: false}, {Name: "none_matches", Type: "BIGINT", Identity: false}, {Name: "updated_unix", Type: "BIGINT", Identity: false}}},
	{Name: "_migrations", Columns: []Column{{Name: "name", Type: "TEXT", Identity: false}}},
	{Name: "_async_migrations", Columns: []Column{{Name: "name", Type: "TEXT", Identity: false}, {Name: "status", Type: "TEXT", Identity: false}, {Name: "started_at", Type: "TEXT", Identity: false}, {Name: "ended_at", Type: "TEXT", Identity: false}, {Name: "error", Type: "TEXT", Identity: false}}},
	{Name: "advert_route_evidence", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: true}, {Name: "tx_id", Type: "BIGINT", Identity: false}, {Name: "bit", Type: "BIGINT", Identity: false}}},
	{Name: "advert_evidence_backfill", Columns: []Column{{Name: "id", Type: "BIGINT", Identity: false}, {Name: "tx_cursor", Type: "BIGINT", Identity: false}, {Name: "obs_cursor", Type: "BIGINT", Identity: false}}},
}

var Indexes = []string{"idx_observations_observer_idx_timestamp", "idx_nodes_last_seen", "idx_observers_last_seen", "idx_inactive_nodes_last_seen", "idx_transmissions_hash", "idx_transmissions_first_seen", "idx_transmissions_payload_type", "idx_client_recept_heard_geo", "idx_client_recept_latlon", "idx_client_recept_rxat", "idx_cro_prune", "idx_cro_hash", "idx_cro_forwarder", "idx_cro_scope", "idx_crf_prune", "idx_crf_track", "idx_ndr_target", "idx_ndr_prune", "idx_observations_transmission_id", "idx_observations_observer_idx", "idx_observations_timestamp", "idx_observations_dedup", "idx_observer_metrics_timestamp", "idx_tx_channel_hash", "idx_dropped_observer", "idx_dropped_node", "idx_nodes_foreign_advert", "idx_transmissions_from_pubkey", "idx_tx_code1", "idx_observations_tx_ts", "idx_transmissions_channel_hash_payload", "idx_observers_iata_norm", "idx_tx_scope_name", "idx_tx_last_seen_zero"}
