package dbschema

import (
	"strings"
	"testing"
)

func TestPostgresManifestPreservesTelemetry(t *testing.T) {
	if len(Tables) != 18 {
		t.Fatalf("telemetry manifest has %d tables, want 18", len(Tables))
	}
	for _, name := range []string{"nodes", "inactive_nodes", "observers", "transmissions", "observations", "observer_metrics", "neighbor_edges", "dropped_packets", "client_receptions", "client_observers", "client_rx_observations", "client_rf_samples", "node_declared_regions", "scope_match_totals", "_migrations", "_async_migrations", "advert_route_evidence", "advert_evidence_backfill"} {
		found := false
		for _, table := range Tables {
			if table.Name == name {
				found = true
			}
		}
		if !found {
			t.Errorf("manifest missing %s", name)
		}
	}
	if !strings.Contains(SchemaSQL, "rowid BIGINT GENERATED BY DEFAULT AS IDENTITY") {
		t.Error("observer identity must be explicit and importable")
	}
	if strings.Contains(strings.ToUpper(SchemaSQL), "JSONB") {
		t.Error("raw JSON must remain text")
	}
}
