-- Canonical PostgreSQL telemetry schema. Raw JSON and timestamp strings remain TEXT COLLATE "C".
CREATE TABLE nodes (
    public_key TEXT COLLATE "C" PRIMARY KEY,
    name TEXT COLLATE "C",
    role TEXT COLLATE "C",
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    last_seen TEXT COLLATE "C",
    first_seen TEXT COLLATE "C",
    advert_count BIGINT DEFAULT 0,
    battery_mv BIGINT,
    temperature_c DOUBLE PRECISION,
    foreign_advert BIGINT DEFAULT 0,
    default_scope TEXT COLLATE "C",
    configured_scope TEXT COLLATE "C",
    configured_scope_at TEXT COLLATE "C",
    multibyte_sup BIGINT NOT NULL DEFAULT 0,
    multibyte_evidence TEXT COLLATE "C"
);

CREATE TABLE inactive_nodes (
    public_key TEXT COLLATE "C" PRIMARY KEY,
    name TEXT COLLATE "C",
    role TEXT COLLATE "C",
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    last_seen TEXT COLLATE "C",
    first_seen TEXT COLLATE "C",
    advert_count BIGINT DEFAULT 0,
    battery_mv BIGINT,
    temperature_c DOUBLE PRECISION,
    foreign_advert BIGINT DEFAULT 0,
    default_scope TEXT COLLATE "C",
    configured_scope TEXT COLLATE "C",
    configured_scope_at TEXT COLLATE "C",
    multibyte_sup BIGINT NOT NULL DEFAULT 0,
    multibyte_evidence TEXT COLLATE "C"
);

CREATE TABLE observers (
    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id TEXT COLLATE "C" PRIMARY KEY,
    name TEXT COLLATE "C",
    iata TEXT COLLATE "C",
    last_seen TEXT COLLATE "C",
    first_seen TEXT COLLATE "C",
    packet_count BIGINT DEFAULT 0,
    model TEXT COLLATE "C",
    firmware TEXT COLLATE "C",
    client_version TEXT COLLATE "C",
    radio TEXT COLLATE "C",
    battery_mv BIGINT,
    uptime_secs BIGINT,
    noise_floor DOUBLE PRECISION,
    inactive BIGINT DEFAULT 0,
    last_packet_at TEXT COLLATE "C" DEFAULT NULL,
    clock_skew_seconds BIGINT DEFAULT NULL,
    clock_skew_count_24h BIGINT DEFAULT 0,
    clock_last_naive_at TEXT COLLATE "C" DEFAULT NULL,
    can_relay BIGINT DEFAULT 1,
    can_relay_seen BIGINT DEFAULT 0
);

CREATE TABLE transmissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_hex TEXT COLLATE "C" NOT NULL,
    hash TEXT COLLATE "C" NOT NULL UNIQUE,
    first_seen TEXT COLLATE "C" NOT NULL,
    route_type BIGINT,
    payload_type BIGINT,
    payload_version BIGINT,
    decoded_json TEXT COLLATE "C",
    from_pubkey TEXT COLLATE "C",
    last_seen BIGINT NOT NULL DEFAULT 0,
    created_at TEXT COLLATE "C" DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    code1 TEXT COLLATE "C",
    code2 TEXT COLLATE "C",
    channel_hash TEXT COLLATE "C",
    scope_name TEXT COLLATE "C"
);

CREATE TABLE observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transmission_id BIGINT NOT NULL REFERENCES transmissions(id),
    observer_idx BIGINT,
    direction TEXT COLLATE "C",
    snr DOUBLE PRECISION,
    rssi DOUBLE PRECISION,
    score DOUBLE PRECISION,
    path_json TEXT COLLATE "C",
    timestamp BIGINT NOT NULL,
    raw_hex TEXT COLLATE "C",
    resolved_path TEXT COLLATE "C"
);

CREATE TABLE observer_metrics (
    observer_id TEXT COLLATE "C" NOT NULL,
    timestamp TEXT COLLATE "C" NOT NULL,
    noise_floor DOUBLE PRECISION,
    tx_air_secs BIGINT,
    rx_air_secs BIGINT,
    recv_errors BIGINT,
    battery_mv BIGINT,
    packets_sent BIGINT,
    packets_recv BIGINT,
    PRIMARY KEY (observer_id, timestamp)
);

CREATE TABLE neighbor_edges (
    node_a TEXT COLLATE "C" NOT NULL,
    node_b TEXT COLLATE "C" NOT NULL,
    count BIGINT DEFAULT 1,
    last_seen TEXT COLLATE "C",
    PRIMARY KEY (node_a, node_b)
);

CREATE TABLE dropped_packets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash TEXT COLLATE "C",
    raw_hex TEXT COLLATE "C",
    reason TEXT COLLATE "C" NOT NULL,
    observer_id TEXT COLLATE "C",
    observer_name TEXT COLLATE "C",
    node_pubkey TEXT COLLATE "C",
    node_name TEXT COLLATE "C",
    dropped_at TEXT COLLATE "C" DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE client_receptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rx_pubkey TEXT COLLATE "C" NOT NULL,
    heard_key TEXT COLLATE "C" NOT NULL,
    heard_keylen BIGINT NOT NULL,
    rssi BIGINT,
    snr DOUBLE PRECISION,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    pos_acc_m DOUBLE PRECISION,
    rx_at TEXT COLLATE "C" NOT NULL,
    ingested_at TEXT COLLATE "C" NOT NULL,
    src TEXT COLLATE "C" NOT NULL,
    UNIQUE(rx_pubkey, heard_key, rx_at)
);

CREATE TABLE client_observers (
    pubkey TEXT COLLATE "C" PRIMARY KEY,
    name TEXT COLLATE "C",
    last_seen TEXT COLLATE "C"
);

CREATE TABLE client_rx_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rx_pubkey TEXT COLLATE "C" NOT NULL,
    rx_at TEXT COLLATE "C" NOT NULL,
    ingested_at TEXT COLLATE "C" NOT NULL,
    pkt_hash TEXT COLLATE "C" NOT NULL,
    route_type BIGINT NOT NULL,
    payload_type BIGINT NOT NULL,
    code1 TEXT COLLATE "C",
    code2 TEXT COLLATE "C",
    scope_name TEXT COLLATE "C",
    hash_size BIGINT NOT NULL,
    hop_count BIGINT NOT NULL,
    path_json TEXT COLLATE "C",
    forwarder TEXT COLLATE "C",
    snr DOUBLE PRECISION,
    rssi BIGINT,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    pos_acc_m DOUBLE PRECISION,
    UNIQUE(rx_pubkey, pkt_hash, rx_at)
);

CREATE TABLE client_rf_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rx_pubkey TEXT COLLATE "C" NOT NULL,
    sampled_at TEXT COLLATE "C" NOT NULL,
    ingested_at TEXT COLLATE "C" NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    pos_acc_m DOUBLE PRECISION,
    stationary BIGINT NOT NULL DEFAULT 0,
    uptime_secs BIGINT NOT NULL,
    battery_mv BIGINT,
    queue_len BIGINT,
    errors BIGINT,
    noise_floor BIGINT,
    last_rssi BIGINT,
    last_snr DOUBLE PRECISION,
    tx_air_secs BIGINT,
    rx_air_secs BIGINT,
    recv BIGINT,
    sent BIGINT,
    flood_rx BIGINT,
    direct_rx BIGINT,
    flood_tx BIGINT,
    direct_tx BIGINT,
    recv_errors BIGINT,
    UNIQUE(rx_pubkey, sampled_at)
);

CREATE TABLE node_declared_regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target TEXT COLLATE "C" NOT NULL,
    rx_pubkey TEXT COLLATE "C" NOT NULL,
    observed_at TEXT COLLATE "C" NOT NULL,
    ingested_at TEXT COLLATE "C" NOT NULL,
    regions_csv TEXT COLLATE "C" NOT NULL,
    truncated BIGINT NOT NULL DEFAULT 0,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    pos_acc_m DOUBLE PRECISION,
    repeater_clock BIGINT,
    UNIQUE(target, rx_pubkey, observed_at)
);

CREATE TABLE scope_match_totals (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    since_unix BIGINT NOT NULL,
    unique_matches BIGINT NOT NULL,
    explicit_over_derived BIGINT NOT NULL,
    ambiguous BIGINT NOT NULL,
    none_matches BIGINT NOT NULL,
    updated_unix BIGINT NOT NULL
);

CREATE TABLE _migrations (
    name TEXT COLLATE "C" PRIMARY KEY
);

CREATE TABLE _async_migrations (
    name TEXT COLLATE "C" PRIMARY KEY,
    status TEXT COLLATE "C" NOT NULL,
    started_at TEXT COLLATE "C" NOT NULL DEFAULT (to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    ended_at TEXT COLLATE "C",
    error TEXT COLLATE "C"
);

CREATE TABLE advert_route_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_id BIGINT NOT NULL REFERENCES transmissions(id) ON DELETE CASCADE,
    bit BIGINT NOT NULL CHECK(bit IN (1,2)),
    UNIQUE(tx_id,bit)
);

CREATE TABLE advert_evidence_backfill (
    id BIGINT PRIMARY KEY CHECK(id=1),
    tx_cursor BIGINT NOT NULL DEFAULT 0,
    obs_cursor BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_observations_observer_idx_timestamp ON observations(observer_idx,timestamp);

CREATE INDEX IF NOT EXISTS idx_nodes_last_seen ON nodes(last_seen);

CREATE INDEX IF NOT EXISTS idx_observers_last_seen ON observers(last_seen);

CREATE INDEX IF NOT EXISTS idx_inactive_nodes_last_seen ON inactive_nodes(last_seen);

CREATE INDEX IF NOT EXISTS idx_transmissions_hash ON transmissions(hash);

CREATE INDEX IF NOT EXISTS idx_transmissions_first_seen ON transmissions(first_seen,id);

CREATE INDEX IF NOT EXISTS idx_transmissions_payload_type ON transmissions(payload_type);

CREATE INDEX IF NOT EXISTS idx_client_recept_heard_geo ON client_receptions(heard_key, heard_keylen, lat, lon);

CREATE INDEX IF NOT EXISTS idx_client_recept_latlon ON client_receptions(lat, lon);

CREATE INDEX IF NOT EXISTS idx_client_recept_rxat ON client_receptions(rx_at);

CREATE INDEX IF NOT EXISTS idx_cro_prune     ON client_rx_observations(rx_at);

CREATE INDEX IF NOT EXISTS idx_cro_hash      ON client_rx_observations(pkt_hash, rx_at);

CREATE INDEX IF NOT EXISTS idx_cro_forwarder ON client_rx_observations(forwarder, rx_at);

CREATE INDEX IF NOT EXISTS idx_cro_scope     ON client_rx_observations(scope_name, rx_at);

CREATE INDEX IF NOT EXISTS idx_crf_prune ON client_rf_samples(sampled_at);

CREATE INDEX IF NOT EXISTS idx_crf_track ON client_rf_samples(rx_pubkey, sampled_at);

CREATE INDEX IF NOT EXISTS idx_ndr_target ON node_declared_regions(target, observed_at);

CREATE INDEX IF NOT EXISTS idx_ndr_prune  ON node_declared_regions(observed_at);

CREATE INDEX IF NOT EXISTS idx_observations_transmission_id ON observations(transmission_id);

CREATE INDEX IF NOT EXISTS idx_observations_observer_idx ON observations(observer_idx);

CREATE INDEX IF NOT EXISTS idx_observations_timestamp ON observations(timestamp);

CREATE UNIQUE INDEX IF NOT EXISTS idx_observations_dedup ON observations(transmission_id,observer_idx,COALESCE(path_json,''));

CREATE INDEX IF NOT EXISTS idx_observer_metrics_timestamp ON observer_metrics(timestamp);

CREATE INDEX IF NOT EXISTS idx_tx_channel_hash ON transmissions(channel_hash) WHERE payload_type = 5;

CREATE INDEX IF NOT EXISTS idx_dropped_observer ON dropped_packets(observer_id);

CREATE INDEX IF NOT EXISTS idx_dropped_node ON dropped_packets(node_pubkey);

CREATE INDEX IF NOT EXISTS idx_nodes_foreign_advert ON nodes(foreign_advert) WHERE foreign_advert = 1;

CREATE INDEX IF NOT EXISTS idx_transmissions_from_pubkey ON transmissions(from_pubkey);

CREATE INDEX IF NOT EXISTS idx_tx_code1 ON transmissions(code1) WHERE code1 IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_observations_tx_ts ON observations(transmission_id, timestamp);

CREATE INDEX IF NOT EXISTS idx_transmissions_channel_hash_payload ON transmissions(channel_hash, payload_type, first_seen);

CREATE INDEX IF NOT EXISTS idx_observers_iata_norm ON observers(UPPER(TRIM(iata)));

CREATE INDEX IF NOT EXISTS idx_tx_scope_name ON transmissions(scope_name) WHERE scope_name IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tx_last_seen_zero ON transmissions(id) WHERE last_seen=0;

CREATE VIEW packets_v AS SELECT o.id,COALESCE(o.raw_hex,t.raw_hex) AS raw_hex,
to_char(to_timestamp(o.timestamp) AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS') AS timestamp,
obs.id AS observer_id,obs.name AS observer_name,o.direction,o.snr,o.rssi,o.score,t.hash,
t.route_type,t.payload_type,t.payload_version,o.path_json,t.decoded_json,t.created_at
FROM observations o JOIN transmissions t ON t.id=o.transmission_id
LEFT JOIN observers obs ON obs.rowid=o.observer_idx AND (obs.inactive IS NULL OR obs.inactive=0);
