package main

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"github.com/meshcore-analyzer/dbconfig"
	"github.com/meshcore-analyzer/pgutil"
	"github.com/meshcore-analyzer/pgutil/pgtest"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"
)

// The columns cmd/server's users.db (internal/users schema v4) has; the
// ingestor reads kind, subject, status, decided_at and id.
const testProposalsDDL = `CREATE TABLE IF NOT EXISTS proposals (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kind TEXT NOT NULL,
	subject TEXT NOT NULL,
	status TEXT NOT NULL,
	proposer_id INTEGER,
	reviewer_id INTEGER,
	note TEXT NOT NULL DEFAULT '',
	created_at INTEGER NOT NULL,
	decided_at INTEGER
)`

type testProposal struct {
	subject, status string
	decidedAt       int64
}

func execUsersDB(t *testing.T, path string, stmts ...string) {
	t.Helper()
	db, err := openApprovedFixture(t, approvedFixture(t, path).owner)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	for _, s := range stmts {
		if approvedTestBackend(t) == dbconfig.SQLite && s == testProposalsDDL {
			s = strings.Replace(s, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY", 1)
		}
		if _, err := db.Exec(s); err != nil {
			t.Fatalf("%s: %v", s, err)
		}
	}
	if stmts[0] == testProposalsDDL {
		if approvedTestBackend(t) == dbconfig.SQLite {
			if _, err := db.Exec(`CREATE TABLE IF NOT EXISTS schema_version(version INTEGER NOT NULL); DELETE FROM schema_version; INSERT INTO schema_version VALUES(5)`); err != nil {
				t.Fatal(err)
			}
			return
		}
		f := approvedFixture(t, path)
		for _, stmt := range []string{
			`CREATE TABLE IF NOT EXISTS corescope_schema(version INTEGER NOT NULL, kind TEXT PRIMARY KEY, ready BOOLEAN NOT NULL)`,
			`INSERT INTO corescope_schema VALUES(1,'accounts',true) ON CONFLICT(kind) DO NOTHING`,
			`CREATE OR REPLACE VIEW approved_channels AS SELECT kind,subject,decided_at,id FROM proposals WHERE status='approved'`,
			`GRANT SELECT ON approved_channels,corescope_schema TO ` + f.role,
		} {
			if _, err := db.Exec(stmt); err != nil {
				t.Fatal(err)
			}
		}
	}

}

func writeUsersDB(t *testing.T, path string, rows ...testProposal) {
	t.Helper()
	stmts := []string{testProposalsDDL, `DELETE FROM proposals`}
	for i, r := range rows {
		stmts = append(stmts, fmt.Sprintf(`INSERT INTO proposals (kind, subject, status, created_at, decided_at) VALUES ('hashtag_channel', '%s', '%s', %d, %d)`,
			r.subject, r.status, i, r.decidedAt))
	}
	execUsersDB(t, path, stmts...)
}

func configuredKeys() map[string]string {
	return map[string]string{"Public": "8b3387e9c5cdea6ac9e5edbaa115cd72", "#mesh": deriveHashtagChannelKey("#mesh")}
}

func TestApprovedChannelsQueryMatchesProjection(t *testing.T) {
	path := filepath.Join(t.TempDir(), "projection.db")
	writeUsersDB(t, path, testProposal{"#fixture", "approved", 1})
	reader := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer reader.Close()
	if _, err := reader.readApproved(); err != nil {
		t.Fatal(err)
	}
}

func TestApprovedChannelsRejectsIncompleteAccountImport(t *testing.T) {
	if approvedTestBackend(t) != dbconfig.Postgres {
		t.Skip("PostgreSQL import readiness marker; SQLite schema completeness is tested separately")
	}
	path := filepath.Join(t.TempDir(), "account-import-gate.db")
	writeUsersDB(t, path, testProposal{"#fixture", "approved", 1})
	reader := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer reader.Close()
	reader.refresh()
	if _, ok := reader.Snapshot()["#fixture"]; !ok {
		t.Fatal("projection reader with readiness metadata could not load a verified account store")
	}
	execUsersDB(t, path, `UPDATE corescope_schema SET ready=false WHERE kind='accounts'`, `DELETE FROM proposals`)
	if _, err := reader.readApproved(); err == nil {
		t.Fatal("partially imported account data was accepted")
	}
	reader.refresh()
	if _, ok := reader.Snapshot()["#fixture"]; !ok {
		t.Fatal("incomplete account import discarded the last good approved keys")
	}
	execUsersDB(t, path, `UPDATE corescope_schema SET ready=true,version=2 WHERE kind='accounts'`)
	if _, err := reader.readApproved(); err == nil {
		t.Fatal("future account schema version was accepted")
	}
}

func TestChannelKeySetOffReturnsConfiguredMap(t *testing.T) {
	cfgd := configuredKeys()
	s := newApprovedTestKeySet(t, cfgd, filepath.Join(t.TempDir(), "users.db"), 128)
	if reflect.ValueOf(s.Snapshot()).Pointer() != reflect.ValueOf(cfgd).Pointer() {
		t.Fatal("before any refresh the decoder must get the very map loadChannelKeys built")
	}
}

func TestChannelKeySetLoadsApproved(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path,
		testProposal{"#mycity", "approved", 10}, testProposal{"#waiting", "pending", 0},
		testProposal{"#nope", "rejected", 11}, testProposal{"#gone", "revoked", 12})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	snap := s.Snapshot()
	if snap["#mycity"] != deriveHashtagChannelKey("#mycity") {
		t.Fatalf("#mycity key = %q", snap["#mycity"])
	}
	for _, n := range []string{"#waiting", "#nope", "#gone"} {
		if _, ok := snap[n]; ok {
			t.Errorf("%s decrypted without approval", n)
		}
	}
	if snap["Public"] == "" || snap["#mesh"] == "" || len(snap) != 3 {
		t.Fatalf("snapshot = %v; want the configured keys plus #mycity", snap)
	}
}

func TestChannelKeySetConfiguredNameWins(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mesh", "approved", 1})
	cfgd := configuredKeys()
	cfgd["#mesh"] = "00112233445566778899aabbccddeeff"
	s := newApprovedTestKeySet(t, cfgd, path, 128)
	defer s.Close()
	s.refresh()
	if got := s.Snapshot()["#mesh"]; got != "00112233445566778899aabbccddeeff" {
		t.Fatalf("#mesh = %q; the configured key must win", got)
	}
	// Revoking the proposal leaves the configured channel decrypted.
	execUsersDB(t, path, `UPDATE proposals SET status = 'revoked'`)
	s.refresh()
	if got := s.Snapshot()["#mesh"]; got != "00112233445566778899aabbccddeeff" {
		t.Fatalf("after revoke #mesh = %q", got)
	}
}

func TestChannelKeySetRevokeRemovesKeyOnNextRefresh(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	before := s.Snapshot()
	execUsersDB(t, path, `UPDATE proposals SET status = 'revoked' WHERE subject = '#mycity'`)
	s.refresh()
	if _, ok := s.Snapshot()["#mycity"]; ok {
		t.Fatal("#mycity still decrypted after revoke")
	}
	if _, ok := before["#mycity"]; !ok {
		t.Fatal("an earlier snapshot must stay unchanged (decoders may still hold it)")
	}
}

func TestChannelKeySetMissingFileKeepsConfiguredAndLogsOnce(t *testing.T) {
	var buf bytes.Buffer
	log.SetOutput(&buf)
	defer log.SetOutput(os.Stderr)
	path := filepath.Join(t.TempDir(), "users.db")
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	s.refresh()
	if len(s.Snapshot()) != 2 {
		t.Fatalf("snapshot = %v; want the configured keys", s.Snapshot())
	}
	if n := strings.Count(buf.String(), "approved channels unavailable"); n != 1 {
		t.Fatalf("logged %d times; want once:\n%s", n, buf.String())
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatal("the ingestor created users.db")
	}
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	s.refresh()
	if _, ok := s.Snapshot()["#mycity"]; !ok {
		t.Fatal("users.db appearing later is picked up")
	}
}

func TestChannelKeySetReadErrorKeepsLastGoodSet(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	statement := `DROP VIEW approved_channels`
	if approvedTestBackend(t) == dbconfig.SQLite {
		statement = `DROP TABLE proposals`
	}
	execUsersDB(t, path, statement)
	s.refresh()
	if _, ok := s.Snapshot()["#mycity"]; !ok {
		t.Fatal("a failing read removed an approved key")
	}
}

func TestChannelKeySetSkipsNamesThatFailTheRules(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path,
		testProposal{"#public", "approved", 1}, testProposal{"nohash", "approved", 2},
		testProposal{"#" + strings.Repeat("a", 31), "approved", 3}, testProposal{"#ok", "approved", 4})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	snap := s.Snapshot()
	if len(snap) != 3 || snap["#ok"] == "" {
		t.Fatalf("snapshot = %v; want configured + #ok only", snap)
	}
}

func TestChannelKeySetCapKeepsOldestApprovals(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#c", "approved", 30}, testProposal{"#a", "approved", 10}, testProposal{"#b", "approved", 20})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 2)
	defer s.Close()
	s.refresh()
	snap := s.Snapshot()
	if snap["#a"] == "" || snap["#b"] == "" || snap["#c"] != "" {
		t.Fatalf("snapshot = %v; want #a and #b (oldest decisions) only", snap)
	}
}

func TestChannelKeySetIsReadOnly(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	_, err := s.db.Exec(`INSERT INTO proposals (kind, subject, status, created_at) VALUES ('hashtag_channel', '#x', 'approved', 1)`)
	if err == nil || !strings.Contains(strings.ToLower(err.Error()), "read") {
		t.Fatalf("write through the ingestor's users.db handle: err = %v; want a read-only refusal", err)
	}
	if approvedTestBackend(t) == dbconfig.Postgres {
		if _, err := s.db.Exec(`SET default_transaction_read_only=off`); err != nil {
			t.Fatal(err)
		}
		if _, err := s.db.Query(`SELECT * FROM proposals`); err == nil {
			t.Fatal("projection reader can read proposals table")
		}
	}

}

// The server keeps users.db in WAL mode with a writer connection open.
func TestChannelKeySetReadsWALWithOpenWriter(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	w, err := openApprovedFixture(t, approvedFixture(t, path).owner)
	if err != nil {
		t.Fatal(err)
	}
	defer w.Close()
	w.SetMaxOpenConns(1)

	if _, err := w.Exec(`INSERT INTO proposals (kind, subject, status, created_at, decided_at) VALUES ('hashtag_channel', '#walcity', 'approved', 9, 9)`); err != nil {
		t.Fatal(err)
	}
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	if s.Snapshot()["#walcity"] == "" || s.Snapshot()["#mycity"] == "" {
		t.Fatalf("snapshot = %v; want both approved names", s.Snapshot())
	}
}

func grpTxtFor(t testing.TB, channelName, text string) []byte {
	key := deriveHashtagChannelKey(channelName)
	inner := append([]byte{1, 0, 0, 0, 0}, []byte(text)...)
	ctHex, macHex := buildChannelEncrypted(key, inner)
	kb, _ := hex.DecodeString(key)
	ct, _ := hex.DecodeString(ctHex)
	mac, _ := hex.DecodeString(macHex)
	h := sha256.Sum256(kb)
	return append(append([]byte{h[0]}, mac...), ct...)
}

// Run with -race: decoders read snapshots while refresh swaps them.
func TestChannelKeySetConcurrentDecodeWhileSwapping(t *testing.T) {
	path := filepath.Join(t.TempDir(), "users.db")
	writeUsersDB(t, path, testProposal{"#mycity", "approved", 1})
	s := newApprovedTestKeySet(t, configuredKeys(), path, 128)
	defer s.Close()
	s.refresh()
	buf := grpTxtFor(t, "#mycity", "alice: hi")
	stop := make(chan struct{})
	var wg sync.WaitGroup
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				select {
				case <-stop:
					return
				default:
				}
				if p := decodeGrpTxt(buf, s.Snapshot()); p.Type == "CHAN" && p.Channel != "#mycity" {
					t.Errorf("decoded as %q", p.Channel)
					return
				}
			}
		}()
	}
	for i := 0; i < 50; i++ {
		status := "revoked"
		if i%2 == 1 {
			status = "approved"
		}
		execUsersDB(t, path, `UPDATE proposals SET status = '`+status+`'`)
		s.refresh()
	}
	close(stop)
	wg.Wait()
	if p := decodeGrpTxt(buf, s.Snapshot()); p.Type != "CHAN" || p.Channel != "#mycity" {
		t.Fatalf("final decode = %+v; want #mycity (last state approved)", p)
	}
}

// Perf evidence for the PR: worst case (no key opens the packet), a
// realistic configured set (320 keys, the size of channel-rainbow.json plus
// Public) alone vs plus 128 approved keys (the maxApproved default).
func BenchmarkDecodeGrpTxtApprovedKeys(b *testing.B) {
	buf := grpTxtFor(b, "#nobody-has-this", "x: y")
	base := configuredKeys()
	for i := len(base); i < 320; i++ {
		name := fmt.Sprintf("#rainbow%03d", i)
		base[name] = deriveHashtagChannelKey(name)
	}
	names := make([]string, 128)
	for i := range names {
		names[i] = fmt.Sprintf("#bench%03d", i)
	}
	withApproved, _ := mergeApprovedKeys(base, names)
	for _, c := range []struct {
		name string
		keys map[string]string
	}{{"configured", base}, {"plus128approved", withApproved}} {
		b.Run(c.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				decodeGrpTxt(buf, c.keys)
			}
		})
	}
}

func TestApprovedChannelsConfig(t *testing.T) {
	t.Setenv("DB_PATH", "")
	dir := t.TempDir()
	dbPath := filepath.ToSlash(filepath.Join(dir, "data", "meshcore.db"))
	load := func(um string) *Config {
		t.Helper()
		p := filepath.Join(dir, "config.json")
		if err := os.WriteFile(p, []byte(`{"dbPath": "`+dbPath+`"`+um+`}`), 0o644); err != nil {
			t.Fatal(err)
		}
		cfg, err := LoadConfig(p)
		if err != nil {
			t.Fatal(err)
		}
		return cfg
	}
	off := load(``)
	if off.ApprovedChannelsEnabled() || off.ApprovedChannelsMax() != 128 || off.ApprovedChannelsURL() != "" {
		t.Fatalf("no block: enabled=%v max=%d path=%q", off.ApprovedChannelsEnabled(), off.ApprovedChannelsMax(), off.ApprovedChannelsURL())
	}
	on := load(`, "userManagement": {"enabled": true, "adminEmails": ["a@example.org"], "mail": {"provider": "brevo"}, "channelProposals": {"enabled": true}}`)
	if !on.ApprovedChannelsEnabled() || on.ApprovedChannelsMax() != 128 {
		t.Fatalf("on: enabled=%v max=%d", on.ApprovedChannelsEnabled(), on.ApprovedChannelsMax())
	}
	for _, um := range []string{
		`, "userManagement": {"enabled": false, "channelProposals": {"enabled": true}}`,
		`, "userManagement": {"enabled": true}`,
		`, "userManagement": {"enabled": true, "channelProposals": {"enabled": false}}`,
	} {
		if load(um).ApprovedChannelsEnabled() {
			t.Errorf("%s resolved as on", um)
		}
	}
	custom := load(`, "userManagement": {"enabled": true, "approvedChannelsDatabaseURL": "postgres://reader@localhost/accounts", "channelProposals": {"enabled": true, "maxApproved": 7}}`)
	if custom.ApprovedChannelsURL() != "postgres://reader@localhost/accounts" || custom.ApprovedChannelsMax() != 7 {
		t.Fatalf("custom: path=%q max=%d", custom.ApprovedChannelsURL(), custom.ApprovedChannelsMax())
	}
	if load(`, "userManagement": {"enabled": true, "channelProposals": {"enabled": true, "maxApproved": -3}}`).ApprovedChannelsMax() != 128 {
		t.Fatal("negative maxApproved must fall back to 128")
	}
}

// The startup line shows the absolute users.db path, so a relative path
// resolved against another working directory than the server's is visible.
func TestApprovedChannelsSourceLogRedactsCredentials(t *testing.T) {
	var buf bytes.Buffer
	prev := log.Writer()
	log.SetOutput(&buf)
	defer log.SetOutput(prev)
	logApprovedChannelsSource("postgres://reader:secret-password@localhost/accounts")
	if strings.Contains(buf.String(), "secret-password") || strings.Contains(buf.String(), "postgres://") {
		t.Fatal("database URL leaked in log")
	}
}

type approvedFixtureDB struct{ owner, reader, role string }

var approvedFixtures sync.Map

func approvedFixture(t *testing.T, key string) approvedFixtureDB {
	t.Helper()
	if approvedTestBackend(t) == dbconfig.SQLite {
		return approvedFixtureDB{owner: key, reader: key}
	}
	key = t.Name() + "|" + key
	if v, ok := approvedFixtures.Load(key); ok {
		return v.(approvedFixtureDB)
	}
	owner := pgtest.NewSchema(t)
	u, _ := url.Parse(owner)
	schema := u.Query().Get("search_path")
	role := schema + "_reader"
	db, err := pgutil.Open(owner, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, stmt := range []string{`CREATE ROLE ` + role + ` LOGIN PASSWORD '` + role + `'`, `GRANT USAGE ON SCHEMA ` + schema + ` TO ` + role} {
		if _, err := db.Exec(stmt); err != nil {
			t.Fatal(err)
		}
	}
	u.User = url.UserPassword(role, role)
	f := approvedFixtureDB{owner, u.String(), role}
	approvedFixtures.Store(key, f)
	t.Cleanup(func() {
		approvedFixtures.Delete(key)
		db.Exec(`DROP OWNED BY ` + role)
		db.Exec(`DROP ROLE ` + role)
		db.Close()
	})
	return f
}
func newApprovedTestKeySet(t *testing.T, configured map[string]string, key string, max int) *channelKeySet {
	return newChannelKeySet(configured, approvedFixture(t, key).reader, max)
}

func approvedTestBackend(t *testing.T) dbconfig.Backend {
	t.Helper()
	switch os.Getenv("CORESCOPE_TEST_BACKEND") {
	case "", "sqlite":
		return dbconfig.SQLite
	case "postgres":
		return dbconfig.Postgres
	default:
		t.Fatal("invalid CORESCOPE_TEST_BACKEND")
		return ""
	}
}
func openApprovedFixture(t *testing.T, path string) (*sql.DB, error) {
	t.Helper()
	if approvedTestBackend(t) == dbconfig.Postgres {
		return pgutil.Open(path, false)
	}
	uri, err := dbconfig.SQLiteURI(path, url.Values{"_journal_mode": {"WAL"}, "_busy_timeout": {"5000"}})
	if err != nil {
		return nil, err
	}
	return sql.Open("sqlite3", uri)
}

func TestApprovedChannelsStorageChoiceDoesNotFallback(t *testing.T) {
	path := filepath.Join(t.TempDir(), "accounts.db")
	// A selected PostgreSQL target cannot fall back even when a local file exists.
	if approvedTestBackend(t) == dbconfig.SQLite {
		writeUsersDB(t, path, testProposal{"#local", "approved", 1})
	}
	s := newChannelKeySetStorage(configuredKeys(), dbconfig.Storage{Backend: dbconfig.Postgres, UsersDBPath: path}, 128)
	defer s.Close()
	if _, err := s.readApproved(); err != errUsersDBMissing {
		t.Fatalf("missing PostgreSQL target error=%v", err)
	}
	s.refresh()
	if len(s.Snapshot()) != 2 {
		t.Fatal("invalid backend selection added account keys")
	}
}

func TestApprovedChannelsSQLiteVersionsAndLiteralPath(t *testing.T) {
	if approvedTestBackend(t) != dbconfig.SQLite {
		t.Skip("native SQLite contract")
	}
	path := filepath.Join(t.TempDir(), "account # % ü.db")
	writeUsersDB(t, path, testProposal{"#local", "approved", 1})
	s := newChannelKeySetStorage(configuredKeys(), dbconfig.Storage{Backend: dbconfig.SQLite, UsersDBPath: path, ApprovedChannelsDatabaseURL: "postgres://unused.invalid/accounts"}, 128)
	defer s.Close()
	for _, version := range []int{4, 5, 6} {
		execUsersDB(t, path, fmt.Sprintf(`UPDATE schema_version SET version=%d`, version))
		names, err := s.readApproved()
		if err != nil || len(names) != 1 || names[0] != "#local" {
			t.Fatalf("version%d names=%v,%v", version, names, err)
		}
	}
	s.refresh()
	for _, version := range []int{3, 7} {
		execUsersDB(t, path, fmt.Sprintf(`UPDATE schema_version SET version=%d`, version))
		if _, err := s.readApproved(); err == nil {
			t.Fatalf("unsupported version%d accepted", version)
		}
		s.refresh()
		if s.Snapshot()["#local"] == "" {
			t.Fatal("unsupported schema removed last good key")
		}
	}
	if s.db.Stats().MaxOpenConnections != 1 {
		t.Fatal("account reader pool is not bounded")
	}
	// mode=ro remains authoritative even when a caller disables query_only.
	if _, err := s.db.Exec(`PRAGMA query_only=OFF`); err != nil {
		t.Fatal(err)
	}
	if _, err := s.db.Exec(`DELETE FROM proposals`); err == nil {
		t.Fatal("SQLite account reader became writable")
	}
}
