package main

import (
	"database/sql"
	"testing"
)

// Deliberately partial fixtures declare the table shapes they test, then
// ensurePreparable supplies the minimum surface required by OpenDB's prepared
// statements. It never creates or modifies a runtime database.
var preparableTables = []string{
	`CREATE TABLE IF NOT EXISTS transmissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, hash TEXT)`,
	`CREATE TABLE IF NOT EXISTS observations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, timestamp TEXT)`,
	`CREATE TABLE IF NOT EXISTS nodes (public_key TEXT PRIMARY KEY)`,
	`CREATE TABLE IF NOT EXISTS observers (rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, id TEXT)`,
}

// preparableColumns are added when absent. A fixture that already declared the
// table keeps its own definition, so only the missing columns get appended.
var preparableColumns = []struct{ table, column, decl string }{
	{"transmissions", "hash", "TEXT"},
	{"observations", "timestamp", "TEXT"},
	{"nodes", "name", "TEXT"},
	{"nodes", "role", "TEXT"},
	{"nodes", "last_seen", "TEXT"},
	{"observers", "inactive", "INTEGER"},
}

// ensurePreparable makes conn's schema sufficient for prepareStatements.
// It is idempotent and never overwrites an existing table or column.
func ensurePreparable(tb testing.TB, conn *sql.DB) {
	tb.Helper()
	for _, ddl := range preparableTables {
		if _, err := conn.Exec(ddl); err != nil {
			tb.Fatalf("ensurePreparable: %v\nSQL: %s", err, ddl)
		}
	}
	for _, c := range preparableColumns {
		_, err := conn.Exec("ALTER TABLE " + c.table + " ADD COLUMN IF NOT EXISTS " + c.column + " " + c.decl)
		// "duplicate column name" means the fixture already declared it.
		if err != nil {
			tb.Fatalf("ensurePreparable: add %s.%s: %v", c.table, c.column, err)
		}
	}
}

// TestEnsurePreparableMatchesPrepareStatements keeps the helper honest. If a new
// prepared statement references a table or column ensurePreparable does not
// create, it fails here rather than as a confusing OpenDB error in whichever
// fixture happens to be thinnest.
func TestEnsurePreparableMatchesPrepareStatements(t *testing.T) {
	conn, err := openPostgresTestDB(t)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	// prepareStatements compiles against a pooled connection; pin the pool so
	// the in-memory database the DDL landed in is the one it prepares against.
	conn.SetMaxOpenConns(1)
	ensurePreparable(t, conn)

	db := &DB{conn: conn}
	if err := db.prepareStatements(); err != nil {
		t.Fatalf("prepareStatements against the minimal preparable schema: %v\n"+
			"Add the missing table/column to preparableTables or preparableColumns.", err)
	}
}
