package users

import (
	"database/sql"
	"errors"
	"fmt"
)

var migrations = [][]string{
	{ // v1: sub-project A
		`CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email TEXT COLLATE "C" NOT NULL UNIQUE,
			display_name TEXT COLLATE "C" NOT NULL,
			password_hash TEXT COLLATE "C" NOT NULL,
			role TEXT COLLATE "C" NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
			status TEXT COLLATE "C" NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','disabled')),
			created_at BIGINT NOT NULL,
			activated_at BIGINT,
			activated_by BIGINT,
			last_login_at BIGINT,
			email_bouncing BIGINT NOT NULL DEFAULT 0 CHECK (email_bouncing IN (0,1))
		)`,
		`CREATE TABLE sessions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			csrf_token TEXT COLLATE "C" NOT NULL,
			created_at BIGINT NOT NULL,
			expires_at BIGINT NOT NULL,
			last_seen_at BIGINT NOT NULL,
			user_agent TEXT COLLATE "C" NOT NULL DEFAULT ''
		)`,
		`CREATE INDEX sessions_user ON sessions(user_id)`,
		`CREATE TABLE tokens (
			token_hash TEXT COLLATE "C" PRIMARY KEY,
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			purpose TEXT COLLATE "C" NOT NULL CHECK (purpose IN ('activate','reset','email_change')),
			new_email TEXT COLLATE "C",
			expires_at BIGINT NOT NULL,
			used_at BIGINT
		)`,
		`CREATE INDEX tokens_user ON tokens(user_id, purpose)`,
		`CREATE TABLE audit_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			at BIGINT NOT NULL,
			actor_user_id BIGINT,
			action TEXT COLLATE "C" NOT NULL,
			target_user_id BIGINT,
			detail TEXT COLLATE "C" NOT NULL DEFAULT '{}'
		)`,
		`CREATE INDEX audit_target ON audit_log(target_user_id)`,
		`CREATE INDEX audit_actor ON audit_log(actor_user_id)`,
		`CREATE TABLE mail_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
			to_email TEXT COLLATE "C" NOT NULL,
			purpose TEXT COLLATE "C" NOT NULL,
			provider_message_id TEXT COLLATE "C",
			sent_at BIGINT NOT NULL,
			last_event TEXT COLLATE "C" NOT NULL DEFAULT 'sent',
			last_event_at BIGINT NOT NULL,
			last_reason TEXT COLLATE "C" NOT NULL DEFAULT ''
		)`,
		`CREATE INDEX mail_user ON mail_log(user_id)`,
		`CREATE UNIQUE INDEX mail_msgid ON mail_log(provider_message_id) WHERE provider_message_id IS NOT NULL`,
		`CREATE TABLE mail_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			mail_id BIGINT NOT NULL REFERENCES mail_log(id) ON DELETE CASCADE,
			event TEXT COLLATE "C" NOT NULL,
			at BIGINT NOT NULL,
			reason TEXT COLLATE "C" NOT NULL DEFAULT '',
			UNIQUE (mail_id, event, at)
		)`,
	},
	{ // v2: sub-project B, settings sync (one document per user)
		`CREATE TABLE user_settings (
			user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			doc TEXT COLLATE "C" NOT NULL,
			revision BIGINT NOT NULL,
			generation TEXT COLLATE "C" NOT NULL,
			updated_at BIGINT NOT NULL
		)`,
	},
	{ // v3: sub-project C, global audit list ordered and filtered by time
		`CREATE INDEX audit_at ON audit_log(at)`,
	},
	{ // v4: sub-project D, proposals (one generic table; this version ships the kind 'hashtag_channel')
		`CREATE TABLE proposals (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			kind TEXT COLLATE "C" NOT NULL,
			subject TEXT COLLATE "C" NOT NULL,
			status TEXT COLLATE "C" NOT NULL CHECK (status IN ('pending','approved','rejected','revoked')),
			proposer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
			reviewer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
			note TEXT COLLATE "C" NOT NULL DEFAULT '',
			created_at BIGINT NOT NULL,
			decided_at BIGINT
		)`,
		`CREATE UNIQUE INDEX proposals_kind_subject ON proposals(kind, subject)`,
		`CREATE INDEX proposals_status ON proposals(status)`,
	},
	{ // v5: sub-project E, node notifications
		`CREATE TABLE notification_prefs (
			user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
			events TEXT COLLATE "C" NOT NULL DEFAULT '',
			unsub_token TEXT COLLATE "C" NOT NULL UNIQUE,
			updated_at BIGINT NOT NULL
		)`,
		`CREATE TABLE notification_watches (
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			pubkey TEXT COLLATE "C" NOT NULL,
			created_at BIGINT NOT NULL,
			PRIMARY KEY (user_id, pubkey)
		)`,
		`CREATE TABLE notification_state (
			user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			event TEXT COLLATE "C" NOT NULL,
			subject TEXT COLLATE "C" NOT NULL,
			state TEXT COLLATE "C" NOT NULL,
			changed_at BIGINT NOT NULL,
			PRIMARY KEY (user_id, event, subject)
		)`,
	},
}

// SchemaVersion is the account data layout version; PostgreSQL readiness is
// recorded separately so the legacy importer can preserve its source history.
const CurrentSchemaVersion = 5
const PostgresSchemaVersion = 1

// Tables is the dependency-ordered account data manifest (metadata excluded).
func Tables() []string {
	return []string{"users", "sessions", "tokens", "audit_log", "mail_log", "mail_events", "user_settings", "proposals", "notification_prefs", "notification_watches", "notification_state"}
}

// Apply installs account schema using the migration owner's connection. Runtime
// Open never runs DDL. An advisory transaction lock serializes simultaneous
// bootstraps, and all DDL plus the readiness marker commit atomically.
func Apply(db *sql.DB) error {
	return apply(db, true)
}

// ApplyForImport creates the schema with readiness false in the same commit.
// Only the offline importer's verified completion may change it to true.
func ApplyForImport(db *sql.DB) error { return apply(db, false) }

func apply(db *sql.DB, markReady bool) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err := applyTx(tx, markReady); err != nil {
		return err
	}
	return tx.Commit()
}

// ApplyForImportTx lets the offline importer atomically create schema and its
// source-bound progress marker, with readiness false throughout.
func ApplyForImportTx(tx *sql.Tx) error { return applyTx(tx, false) }

func applyTx(tx *sql.Tx, markReady bool) error {
	var err error
	if _, err = tx.Exec(`SELECT pg_advisory_xact_lock(hashtextextended(current_schema(),7289041402))`); err != nil {
		return err
	}
	if _, err = tx.Exec(`CREATE TABLE IF NOT EXISTS corescope_schema (version INTEGER NOT NULL, kind TEXT COLLATE "C" NOT NULL PRIMARY KEY CHECK (kind='accounts'), ready BOOLEAN NOT NULL)`); err != nil {
		return err
	}
	var kind string
	var version int
	var ready bool
	err = tx.QueryRow(`SELECT kind,version,ready FROM corescope_schema`).Scan(&kind, &version, &ready)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return err
	}
	if err == nil && !markReady {
		return errors.New("users: import bootstrap requires a fresh account database")
	}
	if err == nil && (kind != "accounts" || version != PostgresSchemaVersion || !ready) {
		return errors.New("users: incompatible or incomplete PostgreSQL account schema")
	}
	if _, err = tx.Exec(`CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL CHECK (version>=0))`); err != nil {
		return err
	}
	var v, count int
	if err = tx.QueryRow(`SELECT COUNT(*), COALESCE(MAX(version),0) FROM schema_version`).Scan(&count, &v); err != nil {
		return err
	}
	if count > 1 {
		return errors.New("users: invalid account schema version metadata")
	}
	if v > CurrentSchemaVersion {
		return fmt.Errorf("users: database schema version %d is newer than supported %d", v, CurrentSchemaVersion)
	}
	if count == 0 {
		if _, err = tx.Exec(`INSERT INTO schema_version VALUES (0)`); err != nil {
			return err
		}
	}
	for i := v; i < len(migrations); i++ {
		for _, stmt := range migrations[i] {
			if _, err = tx.Exec(stmt); err != nil {
				return fmt.Errorf("users: migration %d: %w", i+1, err)
			}
		}
		if _, err = tx.Exec(`UPDATE schema_version SET version=$1`, i+1); err != nil {
			return err
		}
	}
	if _, err = tx.Exec(`CREATE OR REPLACE VIEW approved_channels AS SELECT kind,subject,decided_at,id FROM proposals WHERE status='approved'`); err != nil {
		return err
	}
	if _, err = tx.Exec(`INSERT INTO corescope_schema(version,kind,ready) VALUES (1,'accounts',$1) ON CONFLICT(kind) DO NOTHING`, markReady); err != nil {
		return err
	}
	return nil
}

// AssertReady rejects missing, unsupported or partially imported account state.
func AssertReady(db *sql.DB) error {
	var kind string
	var version int
	var ready bool
	if err := db.QueryRow(`SELECT kind,version,ready FROM corescope_schema`).Scan(&kind, &version, &ready); err != nil {
		return errors.New("users: account database needs bootstrap before runtime startup")
	}
	if kind != "accounts" || version != PostgresSchemaVersion || !ready {
		return errors.New("users: account database is incompatible or import is incomplete")
	}
	var n, v int
	if err := db.QueryRow(`SELECT COUNT(*),COALESCE(MAX(version),0) FROM schema_version`).Scan(&n, &v); err != nil {
		return errors.New("users: account database needs bootstrap")
	}
	if v > CurrentSchemaVersion {
		return fmt.Errorf("users: database schema version %d is newer than supported %d", v, CurrentSchemaVersion)
	}
	if n != 1 || v != CurrentSchemaVersion {
		return errors.New("users: account database needs bootstrap")
	}
	return nil
}

func (s *Store) SchemaVersion() (int, error) {
	var v int
	err := s.db.QueryRow(`SELECT version FROM schema_version`).Scan(&v)
	return v, err
}
